// resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx
import FormSection from '@/Components/FormSection'
import InputError from '@/Components/InputError'
import { Button } from '@/Components/shadcn/ui/button'
import { Input } from '@/Components/shadcn/ui/input'
import { Label } from '@/Components/shadcn/ui/label'
import { Link, router, useForm, usePage } from '@inertiajs/react'
import { memo, useRef, useState } from 'react'
import { toast } from 'sonner'
import { route } from 'ziggy-js'

export default memo(({ user }) => {
  const { props: { jetstream } } = usePage()
  const [verificationLinkSent, setVerificationLinkSent] = useState(false)
  const [photoPreview, setPhotoPreview] = useState(null)
  const photoRef = useRef(null)

  const form = useForm({
    _method: 'PUT',
    name: user.name,
    email: user.email,
    photo: null,
  })

  const clearPhotoFileInput = () => {
    if (photoRef.current?.value) {
      photoRef.current.value = null
    }
  }

  const updateProfileInformation = (e) => {
    e.preventDefault()
    if (photoRef.current?.files[0]) {
      form.setData('photo', photoRef.current.files[0])
    }

    form.post(route('user-profile-information.update'), {
      errorBag: 'updateProfileInformation',
      preserveScroll: true,
      onSuccess: () => {
        clearPhotoFileInput()
        toast.success('Profile information updated')
      },
    })
  }

  const sendEmailVerification = () => {
    setVerificationLinkSent(true)
  }

  const selectNewPhoto = () => {
    photoRef.current?.click()
  }

  const updatePhotoPreview = () => {
    const photo = photoRef.current?.files[0]
    if (!photo)
      return

    const reader = new FileReader()
    reader.onload = (e) => {
      setPhotoPreview(e.target.result)
    }
    reader.readAsDataURL(photo)
  }

  const deletePhoto = () => {
    router.delete(route('current-user-photo.destroy'), {
      preserveScroll: true,
      onSuccess: () => {
        setPhotoPreview(null)
        clearPhotoFileInput()
        toast.success('Photo deleted')
      },
    })
  }

  return (
    <FormSection
      onSubmit={updateProfileInformation}
      title="Profile Information"
      description="Update your account's profile information and email address."
      form={(
        <>
          {/* Profile Photo */}
          {jetstream.managesProfilePhotos && (
            <div className="col-span-6 sm:col-span-4">
              <input
                ref={photoRef}
                type="file"
                className="hidden"
                onChange={updatePhotoPreview}
              />

              <Label htmlFor="photo">Photo</Label>

              {!photoPreview && user.profile_photo_url && (
                <div className="mt-2">
                  <img
                    src={user.profile_photo_url}
                    alt={user.name}
                    className="size-20 rounded-full object-cover"
                  />
                </div>
              )}

              {photoPreview && (
                <div className="mt-2">
                  <span
                    className="block size-20 rounded-full bg-cover bg-center bg-no-repeat"
                    style={{ backgroundImage: `url('${photoPreview}')` }}
                  />
                </div>
              )}

              <Button
                type="button"
                variant="secondary"
                className="me-2 mt-2"
                onClick={selectNewPhoto}
              >
                Select A New Photo
              </Button>

              {user.profile_photo_path && (
                <Button
                  type="button"
                  variant="secondary"
                  onClick={deletePhoto}
                >
                  Remove Photo
                </Button>
              )}

              <InputError message={form.errors.photo} className="mt-2" />
            </div>
          )}

          {/* Name */}
          <div className="col-span-6 sm:col-span-4">
            <Label htmlFor="name">Name</Label>
            <Input
              id="name"
              type="text"
              value={form.data.name}
              onChange={e => form.setData('name', e.target.value)}
              className="mt-1 block w-full"
              required
              autoComplete="name"
            />
            <InputError message={form.errors.name} className="mt-2" />
          </div>

          {/* Email */}
          <div className="col-span-6 sm:col-span-4">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              value={form.data.email}
              disabled
              className="mt-1 block w-full"
              required
              autoComplete="username"
            />
            <InputError message={form.errors.email} className="mt-2" />

            {jetstream.hasEmailVerification && !user.email_verified_at && (
              <div>
                <p className="mt-2 text-sm">
                  Your email address is unverified.
                  <Link
                    href={route('verification.send')}
                    method="post"
                    type="button"
                    as="button"
                    onClick={sendEmailVerification}
                    className="rounded-md text-sm underline focus:outline-hidden focus:ring-2 focus:ring-offset-2"
                  >
                    Click here to re-send the verification email.
                  </Link>
                </p>

                {verificationLinkSent && (
                  <div className="mt-2 text-sm font-medium">
                    A new verification link has been sent to your email address.
                  </div>
                )}
              </div>
            )}
          </div>
        </>
      )}
      actions={
        <Button disabled={form.processing}>Save</Button>
      }
    />
  )
})

// resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
<script setup>
import FormSection from '@/Components/FormSection.vue'
import InputError from '@/Components/InputError.vue'
import Button from '@/Components/shadcn/ui/button/Button.vue'
import Input from '@/Components/shadcn/ui/input/Input.vue'
import Label from '@/Components/shadcn/ui/label/Label.vue'
import { Link, router, useForm } from '@inertiajs/vue3'
import { inject, ref } from 'vue'
import { toast } from 'vue-sonner'

const props = defineProps({
  user: Object,
})
const route = inject('route')
const form = useForm({
  _method: 'PUT',
  name: props.user.name,
  email: props.user.email,
  photo: null,
})

const verificationLinkSent = ref(null)
const photoPreview = ref(null)
const photoInput = ref(null)

function updateProfileInformation() {
  if (photoInput.value) {
    form.photo = photoInput.value.files[0]
  }

  form.post(route('user-profile-information.update'), {
    errorBag: 'updateProfileInformation',
    preserveScroll: true,
    onSuccess: () => {
      clearPhotoFileInput()
      toast.success('Profile information updated')
    },
  })
}

function sendEmailVerification() {
  verificationLinkSent.value = true
}

function selectNewPhoto() {
  photoInput.value.click()
}

function updatePhotoPreview() {
  const photo = photoInput.value.files[0]

  if (!photo)
    return

  const reader = new FileReader()

  reader.onload = (e) => {
    photoPreview.value = e.target.result
  }

  reader.readAsDataURL(photo)
}

function deletePhoto() {
  router.delete(route('current-user-photo.destroy'), {
    preserveScroll: true,
    onSuccess: () => {
      photoPreview.value = null
      clearPhotoFileInput()
      toast.success('Photo deleted')
    },
  })
}

function clearPhotoFileInput() {
  if (photoInput.value?.value) {
    photoInput.value.value = null
  }
}
</script>

<template>
  <FormSection @submitted="updateProfileInformation">
    <template #title>
      Profile Information
    </template>

    <template #description>
      Update your account's profile information and email address.
    </template>

    <template #form>
      <!-- Profile Photo -->
      <div v-if="$page.props.jetstream.managesProfilePhotos" class="col-span-6 sm:col-span-4">
        <!-- Profile Photo File Input -->
        <input id="photo" ref="photoInput" type="file" class="hidden" @change="updatePhotoPreview">

        <Label for="photo">Photo</Label>

        <!-- Current Profile Photo -->
        <div v-show="!photoPreview" class="mt-2">
          <img :src="user.profile_photo_url" :alt="user.name" class="size-20 rounded-full object-cover">
        </div>

        <!-- New Profile Photo Preview -->
        <div v-show="photoPreview" class="mt-2">
          <span
            class="block size-20 rounded-full bg-cover bg-center bg-no-repeat"
            :style="`background-image: url('${photoPreview}');`"
          />
        </div>

        <Button variant="secondary" class="me-2 mt-2" type="button" @click.prevent="selectNewPhoto">
          Select A New Photo
        </Button>

        <Button
          v-if="user.profile_photo_path" variant="secondary" type="button" class="mt-2"
          @click.prevent="deletePhoto"
        >
          Remove Photo
        </Button>

        <InputError :message="form.errors.photo" class="mt-2" />
      </div>

      <!-- Name -->
      <div class="col-span-6 sm:col-span-4">
        <Label for="name">Name</Label>
        <Input
          id="name" v-model="form.name" type="text" class="mt-1 block w-full" required
          autocomplete="name"
        />
        <InputError :message="form.errors.name" class="mt-2" />
      </div>

      <!-- Email -->
      <div class="col-span-6 sm:col-span-4">
        <Label for="email">Email</Label>
        <Input
          id="email"
          v-model="form.email"
          disabled
          type="email"
          class="mt-1 block w-full"
          required
          autocomplete="username"
        />
        <InputError :message="form.errors.email" class="mt-2" />

        <div v-if="$page.props.jetstream.hasEmailVerification && user.email_verified_at === null">
          <p class="mt-2 text-sm">
            Your email address is unverified.

            <Link
              :href="route('verification.send')" method="post" as="button"
              class="rounded-md text-sm underline focus:outline-hidden focus:ring-2 focus:ring-offset-2"
              @click.prevent="sendEmailVerification"
            >
              Click here to re-send the verification email.
            </Link>
          </p>

          <div v-show="verificationLinkSent" class="mt-2 text-sm font-medium">
            A new verification link has been sent to your email address.
          </div>
        </div>
      </div>
    </template>

    <template #actions>
      <Button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
        Save
      </Button>
    </template>
  </FormSection>
</template>
