// resources/js/Components/ActionSection.vue
<template>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="flex justify-between md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium">
          <slot name="title" />
        </h3>

        <p class="mt-1 text-sm">
          <slot name="description" />
        </p>
      </div>

      <div class="px-4 sm:px-0">
        <slot name="aside" />
      </div>
    </div>

    <div class="mt-5 md:col-span-2 md:mt-0">
      <div class="border px-4 py-5 shadow-xs rounded-lg sm:p-6">
        <slot name="content" />
      </div>
    </div>
  </div>
</template>

// resources/js/Components/ActionSection.jsx
import { memo } from 'react'

export default memo(({
  title,
  description,
  aside,
  content,
  className = '',
}) => {
  return (
    <div className={`md:grid md:grid-cols-3 md:gap-6 ${className}`}>
      <div className="flex justify-between md:col-span-1">
        <div className="px-4 sm:px-0">
          <h3 className="text-lg font-medium">
            {title}
          </h3>

          <p className="mt-1 text-sm">
            {description}
          </p>
        </div>

        <div className="px-4 sm:px-0">
          {aside}
        </div>
      </div>

      <div className="mt-5 md:col-span-2 md:mt-0">
        <div className="border px-4 py-5 shadow-xs rounded-lg sm:p-6">
          {content}
        </div>
      </div>
    </div>
  )
})
