// resources/js/Components/ConfirmsPassword.jsx
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/Components/shadcn/ui/dialog';
import { Input } from '@/Components/shadcn/ui/input';
import { Button } from '@/Components/shadcn/ui/button';
import axios from 'axios';
import { memo, useRef, useState } from 'react';
import InputError from './InputError';

export default memo(function ConfirmsPassword({
  title = 'Confirm Password',
  content = 'For your security, please confirm your password to continue.',
  button = 'Confirm',
  children,
  onConfirmed,
}) {
  const [confirmingPassword, setConfirmingPassword] = useState(false);
  const [form, setForm] = useState({
    password: '',
    error: '',
    processing: false,
  });

  const passwordInput = useRef(null);

  const confirmPassword = () => {
    setForm(prev => ({ ...prev, processing: true }));

    axios.post(route('password.confirm'), {
      password: form.password,
    }).then(() => {
      setForm(prev => ({ ...prev, processing: false }));
      onConfirmed?.(form.password);
      closeModal();
    }).catch((error) => {
      setForm(prev => ({
        ...prev,
        processing: false,
        error: error.response.data.errors.password[0],
      }));
      passwordInput.current?.focus();
    });
  };

  const closeModal = () => {
    setConfirmingPassword(false);
    setForm({
      password: '',
      error: '',
      processing: false,
    });
  };

  const handleKeyUp = (e) => {
    if (e.key === 'Enter') {
      confirmPassword();
    }
  };

  return (
    <span>
      <Dialog open={confirmingPassword} onOpenChange={setConfirmingPassword}>
        <DialogTrigger asChild>
          {children}
        </DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{title}</DialogTitle>
            <DialogDescription>
              {content}
            </DialogDescription>
          </DialogHeader>

          <div className="mt-4">
            <Input
              ref={passwordInput}
              value={form.password}
              onChange={e => setForm(prev => ({ ...prev, password: e.target.value }))}
              type="password"
              className="mt-1 block"
              placeholder="Password"
              autoComplete="current-password"
              onKeyUp={handleKeyUp}
            />

            <InputError message={form.error} className="mt-2" />
          </div>

          <DialogFooter className="mt-4">
            <DialogClose asChild>
              <Button variant="secondary" onClick={closeModal}>
                Cancel
              </Button>
            </DialogClose>

            <Button
              variant="destructive"
              className={`ms-3 ${form.processing ? 'opacity-25' : ''}`}
              disabled={form.processing}
              onClick={confirmPassword}
            >
              {button}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </span>
  );
});

// resources/js/Components/ConfirmsPassword.vue
<script setup>
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/Components/shadcn/ui/dialog'
import Input from '@/Components/shadcn/ui/input/Input.vue'
import axios from 'axios'
import { inject, reactive, ref } from 'vue'
import InputError from './InputError.vue'
import Button from './shadcn/ui/button/Button.vue'

defineProps({
  title: {
    type: String,
    default: 'Confirm Password',
  },
  content: {
    type: String,
    default: 'For your security, please confirm your password to continue.',
  },
  button: {
    type: String,
    default: 'Confirm',
  },
})

const emit = defineEmits(['confirmed'])
const route = inject('route')
const confirmingPassword = ref(false)

const form = reactive({
  password: '',
  error: '',
  processing: false,
})

const passwordInput = ref(null)
function confirmPassword() {
  form.processing = true

  axios.post(route('password.confirm'), {
    password: form.password,
  }).then(() => {
    form.processing = false
    emit('confirmed', form.password)
    closeModal()
  }).catch((error) => {
    form.processing = false
    form.error = error.response.data.errors.password[0]
    passwordInput.value.focus()
  })
}

function closeModal() {
  confirmingPassword.value = false
  form.password = ''
  form.error = ''
}
</script>

<template>
  <span>
    <Dialog v-model:open="confirmingPassword">
      <DialogTrigger>
        <slot />
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{{ title }}</DialogTitle>
          <DialogDescription>
            {{ content }}
          </DialogDescription>
        </DialogHeader>

        <div class="mt-4">
          <Input
            ref="passwordInput"
            v-model="form.password"
            type="password"
            class="mt-1 block"
            placeholder="Password"
            autocomplete="current-password"
            @keyup.enter="confirmPassword"
          />

          <InputError :message="form.error" class="mt-2" />
        </div>

        <DialogFooter class="mt-4">
          <DialogClose as-child>
            <Button variant="secondary" @click="closeModal">
              Cancel
            </Button>
          </DialogClose>

          <Button
            variant="destructive"
            class="ms-3" :class="{ 'opacity-25': form.processing }" :disabled="form.processing"
            @click="confirmPassword"
          >
            {{ button }}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </span>
</template>
