// resources/js/Pages/Auth/Login.vue
<script setup>
import InputError from '@/Components/InputError.vue'
import AuthenticationCardLogo from '@/Components/LogoRedirect.vue'
import Button from '@/Components/shadcn/ui/button/Button.vue'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/shadcn/ui/card'
import Checkbox from '@/Components/shadcn/ui/checkbox/Checkbox.vue'
import Input from '@/Components/shadcn/ui/input/Input.vue'
import Label from '@/Components/shadcn/ui/label/Label.vue'
import Sonner from '@/Components/shadcn/ui/sonner/Sonner.vue'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/Components/shadcn/ui/tabs'
import SocialLoginButton from '@/Components/SocialLoginButton.vue'
import { useSeoMetaTags } from '@/Composables/useSeoMetaTags.js'
import { Link, useForm, usePage } from '@inertiajs/vue3'
import { useLocalStorage } from '@vueuse/core'
import { computed, inject, onMounted } from 'vue'
import { toast } from 'vue-sonner'

const props = defineProps({
  canResetPassword: Boolean,
  status: String,
  availableOauthProviders: Object,
})

const page = usePage()
const route = inject('route')
const activeTab = useLocalStorage('login-active-tab', 'password')

// Form state
const passwordForm = useForm({
  email: 'test@example.com',
  password: 'password',
  remember: false,
})

const loginLinkForm = useForm({
  email: '',
})

// Computed
const hasOauthProviders = computed(() =>
  Object.keys(props.availableOauthProviders || {}).length > 0,
)

const isProcessing = computed(() =>
  passwordForm.processing || loginLinkForm.processing,
)

// Methods
function handlePasswordLogin() {
  passwordForm
    .transform(data => ({
      ...data,
      remember: data.remember ? 'on' : '',
    }))
    .post(route('login'), {
      onFinish: () => passwordForm.reset('password'),
    })
}

function handleLoginLink() {
  loginLinkForm.post(route('login-link.store'), {
    onSuccess: () => {
      loginLinkForm.reset()
      if (page.props.flash.success) {
        toast.success(page.props.flash.success)
      }
    },
    onError: () => {
      if (page.props.flash.error) {
        toast.error(page.props.flash.error)
      }
    },
  })
}

// Lifecycle
onMounted(() => {
  if (page.props.flash.error) {
    toast.error(page.props.flash.error)
  }

  if (page.props.flash.success) {
    toast.success(page.props.flash.success)
  }
})

// SEO
useSeoMetaTags({
  title: 'Log in',
})
</script>

<template>
  <Sonner position="top-center" />

  <div class="flex min-h-screen flex-col items-center justify-center bg-linear-to-b from-background/50 to-background">
    <Card class="mx-auto w-[420px] shadow-lg transition-all duration-300 hover:shadow-xl">
      <!-- Header -->
      <CardHeader>
        <CardTitle class="flex justify-center">
          <AuthenticationCardLogo />
        </CardTitle>
        <CardDescription class="text-center text-2xl font-light">
          Welcome Back
        </CardDescription>
      </CardHeader>

      <CardContent>
        <!-- Status Message -->
        <div v-if="status" class="mb-4 text-sm font-medium text-green-600">
          {{ status }}
        </div>

        <!-- Login Tabs -->
        <Tabs v-model="activeTab" class="w-full">
          <TabsList class="grid w-full grid-cols-2 rounded-lg p-1">
            <TabsTrigger value="password">
              Password
            </TabsTrigger>
            <TabsTrigger value="login-link">
              Login Link
            </TabsTrigger>
          </TabsList>

          <div class="mt-6">
            <!-- Password Login -->
            <TabsContent value="password" class="space-y-4">
              <form @submit.prevent="handlePasswordLogin">
                <div class="grid gap-4">
                  <!-- Email -->
                  <div class="grid gap-2">
                    <Label for="email">Email</Label>
                    <Input
                      id="email"
                      v-model="passwordForm.email"
                      type="email"
                      placeholder="name@example.com"
                      required
                      autofocus
                      autocomplete="username"
                    />
                    <InputError :message="passwordForm.errors.email" />
                  </div>

                  <!-- Password -->
                  <div class="grid gap-2">
                    <div class="flex items-center justify-between">
                      <Label for="password">Password</Label>
                      <Link
                        v-if="canResetPassword"
                        :href="route('password.request')"
                        class="text-sm text-muted-foreground hover:text-primary hover:underline underline-offset-4"
                      >
                        Forgot password?
                      </Link>
                    </div>
                    <Input
                      id="password"
                      v-model="passwordForm.password"
                      type="password"
                      required
                      autocomplete="current-password"
                    />
                    <InputError :message="passwordForm.errors.password" />
                  </div>

                  <!-- Remember Me -->
                  <div class="flex items-center space-x-2">
                    <Checkbox
                      id="remember"
                      v-model:checked="passwordForm.remember"
                      name="remember"
                    />
                    <label for="remember" class="text-sm text-muted-foreground">
                      Remember me
                    </label>
                  </div>

                  <Button
                    type="submit"
                    class="w-full"
                    :class="{ 'opacity-75': passwordForm.processing }"
                    :disabled="isProcessing"
                  >
                    {{ passwordForm.processing ? 'Signing in...' : 'Sign in' }}
                  </Button>
                </div>
              </form>
            </TabsContent>

            <!-- Login Link -->
            <TabsContent value="login-link" class="space-y-4">
              <div class="text-sm text-muted-foreground">
                We'll send you a login link for password-free sign in.
              </div>
              <form @submit.prevent="handleLoginLink">
                <div class="grid gap-4">
                  <div class="grid gap-2">
                    <Label for="login-link-email">Email</Label>
                    <Input
                      id="login-link-email"
                      v-model="loginLinkForm.email"
                      type="email"
                      required
                      placeholder="name@example.com"
                    />
                    <InputError :message="loginLinkForm.errors.email" />
                  </div>

                  <Button
                    type="submit"
                    class="w-full"
                    :class="{ 'opacity-75': loginLinkForm.processing }"
                    :disabled="isProcessing"
                  >
                    {{ loginLinkForm.processing ? 'Sending...' : 'Send Login Link' }}
                  </Button>
                </div>
              </form>
            </TabsContent>
          </div>
        </Tabs>

        <!-- OAuth Section -->
        <div v-if="hasOauthProviders" class="mt-6">
          <div class="relative">
            <div class="absolute inset-0 flex items-center">
              <span class="w-full border-t" />
            </div>
            <div class="relative flex justify-center text-xs uppercase">
              <span class="bg-background px-2 text-muted-foreground">
                Or continue with
              </span>
            </div>
          </div>

          <div class="mt-6 grid gap-2">
            <SocialLoginButton
              v-for="provider in availableOauthProviders"
              :key="provider.slug"
              :provider="provider"
              :disabled="isProcessing"
            />
          </div>
        </div>

        <!-- Sign Up Link -->
        <div class="mt-6 text-center text-sm text-muted-foreground">
          Don't have an account?
          <Link
            :href="route('register')"
            class="font-medium text-primary hover:underline underline-offset-4"
          >
            Sign up
          </Link>
        </div>
      </CardContent>
    </Card>
  </div>
</template>

// resources/js/Pages/Auth/Login.jsx
import InputError from '@/Components/InputError';
import AuthenticationCardLogo from '@/Components/LogoRedirect';
import { Button } from '@/Components/shadcn/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/shadcn/ui/card';
import { Checkbox } from '@/Components/shadcn/ui/checkbox';
import { Input } from '@/Components/shadcn/ui/input';
import { Label } from '@/Components/shadcn/ui/label';
import { Sonner, toast } from '@/Components/shadcn/ui/sonner';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/Components/shadcn/ui/tabs';
import SocialLoginButton from '@/Components/SocialLoginButton';
import { useSeoMetaTags } from '@/Composables/useSeoMetaTags';
import { Link, useForm, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';

export default function Login({ canResetPassword, status, availableOauthProviders }) {
  const { props } = usePage();
  const [activeTab, setActiveTab] = useState(() => {
    try {
      return localStorage.getItem('login-active-tab') || 'password';
    } catch {
      return 'password';
    }
  });

  // Form state
  const passwordForm = useForm({
    email: 'test@example.com',
    password: 'password',
    remember: false,
  });

  const loginLinkForm = useForm({
    email: '',
  });

  // Computed
  const hasOauthProviders = Object.keys(availableOauthProviders || {}).length > 0;
  const isProcessing = passwordForm.processing || loginLinkForm.processing;

  // Methods
  const handlePasswordLogin = (e) => {
    e.preventDefault();
    passwordForm
      .transform((data) => ({
        ...data,
        remember: data.remember ? 'on' : '',
      }))
      .post(route('login'), {
        onFinish: () => passwordForm.reset('password'),
      });
  };

  const handleLoginLink = (e) => {
    e.preventDefault();
    loginLinkForm.post(route('login-link.store'), {
      onSuccess: () => {
        loginLinkForm.reset();
        if (props.flash.success) {
          toast.success(props.flash.success);
        }
      },
      onError: () => {
        if (props.flash.error) {
          toast.error(props.flash.error);
        }
      },
    });
  };

  // Effects
  useEffect(() => {
    if (props.flash.error) {
      toast.error(props.flash.error);
    }

    if (props.flash.success) {
      toast.success(props.flash.success);
    }
  }, [props.flash]);

  useEffect(() => {
    try {
      localStorage.setItem('login-active-tab', activeTab);
    } catch {}
  }, [activeTab]);

  // SEO
  useSeoMetaTags({
    title: 'Log in',
  });

  return (
    <>
      <Sonner position="top-center" />

      <div className="flex min-h-screen flex-col items-center justify-center bg-linear-to-b from-background/50 to-background">
        <Card className="mx-auto w-[420px] shadow-lg transition-all duration-300 hover:shadow-xl">
          {/* Header */}
          <CardHeader>
            <CardTitle className="flex justify-center">
              <AuthenticationCardLogo />
            </CardTitle>
            <CardDescription className="text-center text-2xl font-light">Welcome Back</CardDescription>
          </CardHeader>

          <CardContent>
            {/* Status Message */}
            {status && <div className="mb-4 text-sm font-medium text-green-600">{status}</div>}

            {/* Login Tabs */}
            <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
              <TabsList className="grid w-full grid-cols-2 rounded-lg p-1">
                <TabsTrigger value="password">Password</TabsTrigger>
                <TabsTrigger value="login-link">Login Link</TabsTrigger>
              </TabsList>

              <div className="mt-6">
                {/* Password Login */}
                <TabsContent value="password" className="space-y-4">
                  <form onSubmit={handlePasswordLogin}>
                    <div className="grid gap-4">
                      {/* Email */}
                      <div className="grid gap-2">
                        <Label htmlFor="email">Email</Label>
                        <Input
                          id="email"
                          type="email"
                          value={passwordForm.data.email}
                          onChange={(e) => passwordForm.setData('email', e.target.value)}
                          placeholder="name@example.com"
                          required
                          autoFocus
                          autoComplete="username"
                        />
                        <InputError message={passwordForm.errors.email} />
                      </div>

                      {/* Password */}
                      <div className="grid gap-2">
                        <div className="flex items-center justify-between">
                          <Label htmlFor="password">Password</Label>
                          {canResetPassword && (
                            <Link
                              href={route('password.request')}
                              className="text-sm text-muted-foreground hover:text-primary hover:underline underline-offset-4"
                            >
                              Forgot password?
                            </Link>
                          )}
                        </div>
                        <Input
                          id="password"
                          type="password"
                          value={passwordForm.data.password}
                          onChange={(e) => passwordForm.setData('password', e.target.value)}
                          required
                          autoComplete="current-password"
                        />
                        <InputError message={passwordForm.errors.password} />
                      </div>

                      {/* Remember Me */}
                      <div className="flex items-center space-x-2">
                        <Checkbox
                          id="remember"
                          checked={passwordForm.data.remember}
                          onCheckedChange={(checked) => passwordForm.setData('remember', checked)}
                          name="remember"
                        />
                        <label htmlFor="remember" className="text-sm text-muted-foreground">
                          Remember me
                        </label>
                      </div>

                      <Button
                        type="submit"
                        className={\`w-full \${passwordForm.processing ? 'opacity-75' : ''}\`}
                        disabled={isProcessing}
                      >
                        {passwordForm.processing ? 'Signing in...' : 'Sign in'}
                      </Button>
                    </div>
                  </form>
                </TabsContent>

                {/* Login Link */}
                <TabsContent value="login-link" className="space-y-4">
                  <div className="text-sm text-muted-foreground">
                    We'll send you a login link for password-free sign in.
                  </div>
                  <form onSubmit={handleLoginLink}>
                    <div className="grid gap-4">
                      <div className="grid gap-2">
                        <Label htmlFor="login-link-email">Email</Label>
                        <Input
                          id="login-link-email"
                          type="email"
                          value={loginLinkForm.data.email}
                          onChange={(e) => loginLinkForm.setData('email', e.target.value)}
                          required
                          placeholder="name@example.com"
                        />
                        <InputError message={loginLinkForm.errors.email} />
                      </div>

                      <Button
                        type="submit"
                        className={\`w-full \${loginLinkForm.processing ? 'opacity-75' : ''}\`}
                        disabled={isProcessing}
                      >
                        {loginLinkForm.processing ? 'Sending...' : 'Send Login Link'}
                      </Button>
                    </div>
                  </form>
                </TabsContent>
              </div>
            </Tabs>

            {/* OAuth Section */}
            {hasOauthProviders && (
              <div className="mt-6">
                <div className="relative">
                  <div className="absolute inset-0 flex items-center">
                    <span className="w-full border-t" />
                  </div>
                  <div className="relative flex justify-center text-xs uppercase">
                    <span className="bg-background px-2 text-muted-foreground">Or continue with</span>
                  </div>
                </div>

                <div className="mt-6 grid gap-2">
                  {Object.entries(availableOauthProviders).map(([key, provider]) => (
                    <SocialLoginButton key={key} provider={provider} disabled={isProcessing} />
                  ))}
                </div>
              </div>
            )}

            {/* Sign Up Link */}
            <div className="mt-6 text-center text-sm text-muted-foreground">
              Don't have an account?{' '}
              <Link href={route('register')} className="font-medium text-primary hover:underline">
                Sign up
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </>
  );
}
