// resources/js/Pages/Auth/TwoFactorChallenge.vue
<script setup>
import InputError from '@/Components/InputError.vue'
import AuthenticationCardLogo from '@/Components/LogoRedirect.vue'
import Button from '@/Components/shadcn/ui/button/Button.vue'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/shadcn/ui/card'
import Input from '@/Components/shadcn/ui/input/Input.vue'
import Label from '@/Components/shadcn/ui/label/Label.vue'
import { useSeoMetaTags } from '@/Composables/useSeoMetaTags.js'

import { useForm } from '@inertiajs/vue3'
import { inject, nextTick, ref } from 'vue'

useSeoMetaTags({
  title: 'Two-factor Confirmation',
})

const route = inject('route')
const recovery = ref(false)

const form = useForm({
  code: '',
  recovery_code: '',
})

const recoveryCodeInput = ref(null)
const codeInput = ref(null)

async function toggleRecovery() {
  recovery.value ^= true

  await nextTick()

  if (recovery.value) {
    recoveryCodeInput.value.focus()
    form.code = ''
  }
  else {
    codeInput.value.focus()
    form.recovery_code = ''
  }
}

function submit() {
  form.post(route('two-factor.login'))
}
</script>

<template>
  <div class="flex min-h-screen flex-col items-center justify-center">
    <Card class="mx-auto max-w-lg">
      <CardHeader>
        <CardTitle class="flex justify-center">
          <AuthenticationCardLogo />
        </CardTitle>
        <CardDescription class="text-center text-2xl">
          Two-factor authentication
        </CardDescription>
      </CardHeader>

      <CardContent>
        <div class="mb-4 text-sm">
          <template v-if="!recovery">
            Please confirm access to your account by entering the authentication code provided by your
            authenticator application.
          </template>

          <template v-else>
            Please confirm access to your account by entering one of your emergency recovery codes.
          </template>
        </div>

        <form @submit.prevent="submit">
          <div v-if="!recovery">
            <Label for="code">Code</Label>
            <Input
              id="code" ref="codeInput" v-model="form.code" type="text" inputmode="numeric"
              class="mt-1 block w-full" autofocus autocomplete="one-time-code"
            />
            <InputError class="mt-2" :message="form.errors.code" />
          </div>

          <div v-else>
            <Label for="recovery_code">Recovery Code</Label>
            <Input
              id="recovery_code" ref="recoveryCodeInput" v-model="form.recovery_code" type="text"
              class="mt-1 block w-full" autocomplete="one-time-code"
            />
            <InputError class="mt-2" :message="form.errors.recovery_code" />
          </div>

          <div class="mt-4 flex items-center justify-end">
            <button type="button" class="cursor-pointer text-sm" @click.prevent="toggleRecovery">
              <template v-if="!recovery">
                Use a recovery code
              </template>

              <template v-else>
                Use an authentication code
              </template>
            </button>

            <Button class="ms-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
              Log in
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  </div>
</template>

// resources/js/Pages/Auth/TwoFactorChallenge.jsx
import InputError from '@/Components/InputError';
import AuthenticationCardLogo from '@/Components/LogoRedirect';
import { Button } from '@/Components/shadcn/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/shadcn/ui/card';
import { Input } from '@/Components/shadcn/ui/input';
import { Label } from '@/Components/shadcn/ui/label';
import { useSeoMetaTags } from '@/Composables/useSeoMetaTags';
import { useForm } from '@inertiajs/react';
import { memo, useRef, useState } from 'react';

export default memo(function TwoFactorChallenge() {
  useSeoMetaTags({
    title: 'Two-factor Confirmation',
  });

  const [recovery, setRecovery] = useState(false);

  const form = useForm({
    code: '',
    recovery_code: '',
  });

  const recoveryCodeInput = useRef(null);
  const codeInput = useRef(null);

  const toggleRecovery = () => {
    setRecovery(prev => !prev);
    if (!recovery) {
      form.setData('code', '');
      setTimeout(() => recoveryCodeInput.current?.focus(), 0);
    } else {
      form.setData('recovery_code', '');
      setTimeout(() => codeInput.current?.focus(), 0);
    }
  };

  const submit = (e) => {
    e.preventDefault();
    form.post(route('two-factor.login'));
  };

  return (
    <div className="flex min-h-screen flex-col items-center justify-center">
      <Card className="mx-auto max-w-lg">
        <CardHeader>
          <CardTitle className="flex justify-center">
            <AuthenticationCardLogo />
          </CardTitle>
          <CardDescription className="text-center text-2xl">
            Two-factor authentication
          </CardDescription>
        </CardHeader>

        <CardContent>
          <div className="mb-4 text-sm">
            {!recovery ? (
              'Please confirm access to your account by entering the authentication code provided by your authenticator application.'
            ) : (
              'Please confirm access to your account by entering one of your emergency recovery codes.'
            )}
          </div>

          <form onSubmit={submit}>
            {!recovery ? (
              <div>
                <Label htmlFor="code">Code</Label>
                <Input
                  id="code"
                  ref={codeInput}
                  type="text"
                  inputMode="numeric"
                  value={form.data.code}
                  onChange={e => form.setData('code', e.target.value)}
                  className="mt-1 block w-full"
                  autoFocus
                  autoComplete="one-time-code"
                />
                <InputError className="mt-2" message={form.errors.code} />
              </div>
            ) : (
              <div>
                <Label htmlFor="recovery_code">Recovery Code</Label>
                <Input
                  id="recovery_code"
                  ref={recoveryCodeInput}
                  type="text"
                  value={form.data.recovery_code}
                  onChange={e => form.setData('recovery_code', e.target.value)}
                  className="mt-1 block w-full"
                  autoComplete="one-time-code"
                />
                <InputError className="mt-2" message={form.errors.recovery_code} />
              </div>
            )}

            <div className="mt-4 flex items-center justify-end">
              <button
                type="button"
                className="cursor-pointer text-sm"
                onClick={toggleRecovery}
              >
                {!recovery ? 'Use a recovery code' : 'Use an authentication code'}
              </button>

              <Button
                className={`ms-4 ${form.processing ? 'opacity-25' : ''}`}
                disabled={form.processing}
              >
                Log in
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
});
